name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --legacy-peer-deps
    - name: Run ESLint
      run: npx eslint --fix . --ext .js,.jsx,.ts,.tsx
    - name: Run tests
      run: npm run testFinal
