name: 'CI'

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --legacy-peer-deps
    - name: Run ESLint Fix
      run: npm run fixStyle
    - name: Run ESLint
      run: npm run checkStyle
